basePath: /api/v1
host: localhost:58080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is puzzle internal api server.
  license:
    name: MIT 1.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Puzzle Internal API
  version: 0.1.0
paths: {}
swagger: "2.0"
